### ISSUE TITLE
AWS Autoscaling

### ISSUE THREAD

**Issue by jstarcher** [johnbellone/consul-cookbook#192]
After reading the official documentation on Outage Recovery and seeing that when a server outage occurs the same IP address needs to be used else the raft/peers.json file needs updated it brought me to start looking at this cookbook to see how we can implement autoscaling support. 

Is this something that has been considered in the past or perhaps already exists but isn't documented?

My thoughts are that if it will be too complex to add servers with different IP addresses, perhaps the best approach for durability (not scalability) would be to have a fixed autoscaling group which on first boot will assign a reserved EIP to the node. There might be some challenges around the timing as the failed node would need to be terminated so the EIP could be released for the new node to register with it though.

**Comment by jstarcher** [comment]
Why is this being closed, was it fixed?

**Comment by nicwaller** [comment]
@jstarcher I'm not the maintainer, but maybe I can help.

I think this issue was closed because the question is not within scope for this project. As a Chef cookbook, the focus is on configuration of an individual node (server). A Chef cookbook is not really the right place to be solving problems with clustering.

To address your original question, I'm not sure why you want to use Auto Scaling Groups with Consul servers. Consul servers are normally long-lived, like a database server, whereas ASGs are more appropriate for stateless web applications that are crash-safe. Consul is sensitive to changes of the private IP, so using EIPs doesn't really provide any benefit. The most reliable way to set up Consul clusters in AWS EC2 is to create long-lived, dedicated instances in a VPC with static assignments for the private IP. CloudFormation stacks are well suited to this purpose.

If you still have questions, I suggest directing them to the official [Consul project](https://github.com/hashicorp/consul/issues) unless your question specifically pertains to configuring Consul using this Chef cookbook.

**Comment by chrisferry** [comment]
@nicwaller but nothing in AWS is long-lived. You can't depend on that. You have to build self-healing into the app or the chef cookbook.
