### ISSUE TITLE
consul only binds to localhost 127.0.0.1

### ISSUE THREAD

**Issue by devilldog** [johnbellone/consul-cookbook#193]
Hi, I have deployed consul using the cookbook but the "server" nodes are only binding to 127.0.0.1, i have tried option in the docs but it only works if I manually set client_addr in the config file, how can i set this using the cook book. ?
cheers
Rob

**Comment by tomzo** [comment]
Hi,

I have the same problem. I think I localized the issue - [here](https://github.com/johnbellone/consul-cookbook/blob/master/recipes/service.rb#L111)

It is because adding `client_addr` in default.json is actually conditional only when your consul node is running UI. 

IMO this is should not be like that. consul docs clearly say that `client_addr` is
> The address to which Consul will bind client interfaces, including the HTTP, DNS, and RPC servers. By default, this is "127.0.0.1", allowing only loopback connections. The RPC address is used by other Consul commands, such as consul members, in order to query a running Consul agent.

I think the same problem was reported in #73 and I really do not understand why it was closed. 

`client_addr`  is not an UI-only attribute. It is very confusing to work with this attribute like now.

@devilldog 
My workaround is  to have something like this in wrapper cookbook
```
override['consul']['extra_params'] = { client_addr: '0.0.0.0' }
```
I haven't tested yet.

I'd like to hear what @johnbellone thinks about this attribute. Why is it under UI section in readme and why this conditional assignment is still here?

**Comment by johnbellone** [comment]
@tomzo Did that workaround solve the immediate issue?

My plan is to merge in #126 next week which drastically changes how this cookbook works. We will need to go through significant testing, and I would prefer spending time there to make sure this case is covered.

**Comment by tomzo** [comment]
Yes. It did solve this. 
I'd suggest that in #126 client_addr is treated like in official docs. Don't let it be an ui thing.
