### ISSUE TITLE
Changelog for 2.0.0 should mention breaking changes

### ISSUE THREAD

**Issue by nicwaller** [johnbellone/consul-cookbook#301]
Please mention the removal of `consul_ui` in the Changelog for the 2.0.0 release.

I had to comb through commits and issues to figure out what motivated the major version bump. Eventually I found it was the removal of `consul_ui` in 8a2144f, and upgrading is very easy:
- Upgrade to 2.1 (for #297) to restore functionality for installing web UI
- Remove mentions of the `consul_ui` resource from my own code

Now I'm converging successfully so I assume there were no other breaking changes in 2.0.0.

**Comment by johnbellone** [comment]
I'll mention those changes, but this is an implicit assumption of a major version change.

**Comment by legal90** [comment]
@johnbellone Thanks. Documentation for `consul_installation` resource would be very helpful too. :+1:

**Comment by phs** [comment]
The removal of `consul` from `/usr/local/bin` (and so presence on typical `PATH`) tripped me up as well.

**Comment by gmreburn** [comment]
Version 0.6.1 of Consul added a new -ui command line and ui config option that enables a built-in Consul web UI, making deployment much simpler [GH-1543]. This means a separate install no longer exists for the UI component so you would think that the `consul_ui` is no longer needed; however, in order to support older versions of Consul (<0.6.1), `consul_ui` should not have been removed.

**Comment by legal90** [comment]
Hi all! I'm going to close this issue since v2.0.0 was released a while ago, so I'm not sure that any of maintainers cat/want to groom the changelog for that release (but we are open for Pull-Requests ;) ).

However, today we fully understand the importance of a good changelog, so the recent release v3.0.0 has a good changelog with breaking changes mentioned: https://github.com/johnbellone/consul-cookbook/blob/master/CHANGELOG.md#v300-2017-06-11.
Hopefully, that practice will be followed in further releases.

P.s. http://keepachangelog.com/
