### ISSUE TITLE
When ui_dir is set in windows, ui does not work.  Separate UI download/extraction seems to not be required for current version of consul on Windows.

### ISSUE THREAD

**Issue by jvogt** [johnbellone/consul-cookbook#339]
The current version of consul only needs `ui = true` for the ui to work (at least on Windows).  No separate download required.  But if `ui_dir` is set in the consul.json config file, visiting the ui results in a 404.  Even when it is pointing to a linked location where the ui is actually separately extracted to (as this cookbook's default behavior attempts to do)

I couldn't figure out how to override this option in a way that does not print the `ui_dir` line to the consul config.

Tried various ways of setting `node['consul']['config']['ui_dir']` to `false`, `nil`, `''`, etc.  

Not sure of best way to correct or I would submit a PR myself.

**Comment by drywheat** [comment]
Setting `ui = true` using Consul v0.6.4 on Linux (debian 8.5) results in the following behavior:

1. The webui package is automatically downloaded and installed under `/opt/consul-webui`.
2. The webui installation is symlinked to `/var/lib/consul/ui`.
3. Consul server the UI component correctly.

As of Consul v0.6.4 (possibly earlier):
> -ui - Enables the built-in web UI server and the required HTTP routes. This eliminates the need to maintain the Consul web UI files separately from the binary.

Ideally, setting `ui = true` should just add the option to the main config file. Another attribute could trigger whether or not the consumer wants to install the webui as a separate package, and maybe that's the default behavior for now in order to maintain backwards compatibility.

**Comment by jeffbyrnes** [comment]
#315 resolves this, but a version of this cookbook with those changes hasn’t been released yet.

**Comment by pdf** [comment]
FYI, #315 needs #360 to work as expected.
